// LOGIN
export const LOGIN_REQUEST = "login/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "login/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "login/LOGIN_FAILURE";

// LOGIN
export const LOGOUT_REQUEST = "logout/LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "logout/LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "logout/LOGOUT_FAILURE";

// SIGNUP
export const SIGNUP_REQUEST = "signup/SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "signup/SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "signup/SIGNUP_FAILURE";

// POST_WRITE
export const POST_WRITE_REQUEST = "post/POST_WRITE_REQUEST";
export const POST_WRITE_SUCCESS = "post/POST_WRITE_SUCCESS";
export const POST_WRITE_FAILURE = "post/POST_WRITE_FAILURE";

// POST_LOADING
export const POST_LOADING_REQUEST = "post/POST_LOADING_REQUEST";
export const POST_LOADING_SUCCESS = "post/POST_LOADING_SUCCESS";
export const POST_LOADING_FAILURE = "post/POST_LOADING_FAILURE";

// POST_EDIT
export const POST_EDIT_REQUEST = "post/POST_EDIT_REQUEST";
export const POST_EDIT_SUCCESS = "post/POST_EDIT_SUCCESS";
export const POST_EDIT_FAILURE = "post/POST_EDIT_FAILURE";

// POST_SUBMIT
export const POST_SUBMIT_REQUEST = "post/POST_SUBMIT_REQUEST";
export const POST_SUBMIT_SUCCESS = "post/POST_SUBMIT_SUCCESS";
export const POST_SUBMIT_FAILURE = "post/POST_SUBMIT_FAILURE";
