spring:
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      username: sa
      password:
    url: jdbc:h2:mem:blog

  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

security:
  url:
    login: /api/login
    signup: /api/signup

jwt:
  header: Token
  secret: spring-security-jwt-secret-key-my-blog-project-should-be-bigger-than-512bits
  token-validity-in-seconds: 86400000

file:
  path: /Users/dongwoo-yang/spring-file/

#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE