spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  config:
    import: classpath:/application-local.yml

file:
  path: /Users/dongwoo-yang/spring-file/

security:
  url:
    login: /api/auth/login
    signup: /api/auth/signup
    logout: /api/auth/logout
  jwt:
    header: Token
    secret: spring-security-jwt-secret-key-my-blog-project-should-be-bigger-than-512bits
    token-validity-in-seconds: 86400000
  exclude:
    url:
      - GET /h2-console/**
      - POST /api/auth/signup
      - GET /api/auth/logout
      - GET /api/post/**

#logging:
#  level:
#    org:
#      springframework:
#        security: debug
